USE [BTLWEB]
GO
/****** Object:  Table [dbo].[truyen]    Script Date: 5/15/2022 10:03:29 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[truyen](
	[idTruyen] [nchar](10) NOT NULL,
	[ten] [nchar](255) NOT NULL,
	[nxb] [nchar](255) NOT NULL,
	[rating] [int] NULL,
	[stt] [int] DEFAULT NEXT VALUE FOR GlobalCounter NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK_truyen] PRIMARY KEY CLUSTERED 
(
	[idTruyen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[truyen] ON 
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'50SOG01   ', N'50 Sac Thai                                                                                                                                                                                                                                                    ', N'Vintage Books                                                                                                                                                                                                                                                  ', NULL, 1, N'6041bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN1    ', N'Conan tap 1                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 13, N'1ceae4b4-8ed3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN2    ', N'Conan tap 2                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 16, N'fd12aef8-8fd3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN3    ', N'Conan tap 3                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 17, N'f9816828-96d3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN4    ', N'Conan tap 4                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 19, N'ec4aa2bd-96d3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN5    ', N'Conan tap 5                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 20, N'86dc33f7-99d3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN6    ', N'Conan tap 6                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 21, N'f7c20d1c-9ad3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN7    ', N'Conan tap 7                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 47, N'b1103c22-9fd3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'CONAN8    ', N'Conan tap 8                                                                                                                                                                                                                                                    ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 49, N'9724c43c-a0d3-ec11-bd2b-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM1      ', N'Doremon Tap 1                                                                                                                                                                                                                                                  ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 2, N'6141bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM10     ', N'Doremon Tap 10                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 3, N'6241bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM11     ', N'Doremon  Tap 11                                                                                                                                                                                                                                                ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 4, N'6341bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM2      ', N'Doremon  Tap 2                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 5, N'6441bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM3      ', N'Doremon  Tap 3                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 6, N'6541bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM4      ', N'Doremon  Tap 4                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 7, N'6641bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM5      ', N'Doremon  Tap 5                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 8, N'6741bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM6      ', N'Doremon  Tap 6                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 9, N'6841bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM7      ', N'Doremon Tap 7                                                                                                                                                                                                                                                  ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 10, N'6941bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM8      ', N'Doremon  Tap 8                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 11, N'6a41bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
INSERT [dbo].[truyen] ([idTruyen], [ten], [nxb], [rating], [stt], [rowguid]) VALUES (N'DRM9      ', N'Doremon  Tap 9                                                                                                                                                                                                                                                 ', N'Kim Dong                                                                                                                                                                                                                                                       ', NULL, 12, N'6b41bada-35cd-ec11-bd20-d8f2ca8a1b27')
GO
SET IDENTITY_INSERT [dbo].[truyen] OFF
GO
ALTER TABLE [dbo].[truyen] ADD  CONSTRAINT [MSmerge_df_rowguid_5C980D0758084CF4AE3530B5D478B54E]  DEFAULT (newsequentialid()) FOR [rowguid]
GO
